## ---------------------------------------------------------------------
##
## Copyright (C) 2018 by Michael F. Herbst and contributors
##
## This file is part of pammap.
##
## pammap is free software: you can redistribute it and/or modify
## it under the terms of the GNU Lesser General Public License as published
## by the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## pammap is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public License
## along with pammap. If not, see <http://www.gnu.org/licenses/>.
##
## ---------------------------------------------------------------------

language: cpp
sudo: false

branches:
  only:
    # Only build master and version tags
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
    # Use two threads in parallel
    - CORES=2

addons:
  apt:
    sources: &def_sources
      - ubuntu-toolchain-r-test     # g++ 7 and newer C++ standard library
      - llvm-toolchain-trusty-5.0   # clang-5.0
    packages: &def_packages
      - ninja-build

matrix:
  include:
    #
    # Clang 5.0 (has c++17)
    - addons:
        apt:
          sources: *def_sources
          packages:
            - *def_packages
            - &clang_newest [ libstdc++-7-dev, clang-5.0, libc++-dev, llvm-5.0, clang-tidy-5.0 ]
      compiler: clang
      env: COMPILER="clang-5.0"  # SANITISE=address  TODO Fails for weird reasons
    #
    # gcc-5 (has c++14)
    - addons:
        apt:
          sources: *def_sources
          packages:
            - *def_packages
            - g++-5
      compiler: gcc
      env: COMPILER="gcc-5"
    #
    # gcc-7 (has c++17)
    - addons:
        apt:
          sources: *def_sources
          packages:
            - *def_packages
            - g++-7
      compiler: gcc
      env: COMPILER="gcc-7"
    #
    # Clang tidy
    - addons:
        apt:
          sources: *def_sources
          packages:
            - *def_packages
            - *clang_newest
      compiler: clang
      env: JOB=code_style

script: ci/build.sh
